clean up bashrc

diff --git a/bin/ccheck b/bin/ccheck
--- a/bin/ccheck
+++ b/bin/ccheck
@@ -1,4 +1,10 @@
 #!/bin/bash
+hash cppcheck &>/dev/null
+if [[ 0 -ne $? ]] then
+  echo "cppcheck not found"
+  exit 0
+fi
 GCCINSTALL="/usr/lib/gcc/$(gcc -dumpmachine)/$(gcc -dumpversion)"
-cppcheck -I/usr/local/include -I/usr/include -I ${GCCINSTALL}/include -I ${GCCINSTALL}/include-fixed \
+cppcheck -I/usr/local/include -I/usr/include \
+  -I ${GCCINSTALL}/include -I ${GCCINSTALL}/include-fixed \
   -v -DDUMMY --std=c11 --language=c --enable=all "$@"
